name: Run

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore
      
    - name: Run
      run: dotnet run -c Release --project SortBench
      
    - name: Upload result.csv
      uses: actions/upload-artifact@v2.3.1
      with:
        name: result.zip
        path: result.csv

    - name: Upload plot.svg
      uses: actions/upload-artifact@v2.3.1
      with:
        name: result.zip
        path: plot.svg
